[tools]
run-in-roblox = { source = 'rojo-rbx/run-in-roblox', version = '^0.3' }
tarmac = { source = 'jeparlefrancais/tarmac', version = '^0.7' } # Improved version of tarmac (as of 2/26/2021)
stylua = { source = "JohnnyMorganz/stylua", version = "^0.7" }
selene = { source = 'Kampfkarren/selene', version = '^0.11' }
rojo = { source = 'rojo-rbx/rojo', version = '^6.1' }
