[tools]
selene = { source = 'Kampfkarren/selene', version = '^0.11' }
rojo = { source = 'rojo-rbx/rojo', version = '^7.0.0-alpha' }
tarmac = { source = 'jeparlefrancais/tarmac', version = '^0.7' } # Better version of tarmac, as of 2/26/2021
run-in-roblox = { source = 'rojo-rbx/run-in-roblox', version = '^0.3' }
