[tools] # These tools are used specifically for continuous integration
selene = { source = 'Kampfkarren/selene', version = '^0.11' }
run-in-roblox = { source = 'rojo-rbx/run-in-roblox', version = '^0.3' }
